sudo: required

services:
  - docker

install:
  - docker build -t simple-yum-repo-webserver .
  - docker run -d --name simple-yum-repo-webserver-nofiles simple-yum-repo-webserver
  - docker run -d -v `pwd`/test:/usr/share/nginx/html --name simple-yum-repo-webserver-rpm simple-yum-repo-webserver

script:
  - docker --version
  - bash -x test/wait-for-webserver.sh
  - |
    [ -d ./test/repodata ]
  - find ./test/repodata
  - |
    [ -f ./test/repodata/repomd.xml ]
